import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import '@/styles/globals.css'
import TopBar from "@/components/topBar";
import Footer from "@/components/footer";

const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '700', '900'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <div className="flex flex-col min-h-screen bg-solar-gray-dark overflow-x-auto">
          <TopBar />
          <div className="flex-grow bg-solar-image bg-cover p-3">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
